#lang clotho
;;; virgil-smith.rkt — Xsmith-based random program generator for Virgil.
;;;
;;; Phase 1 coverage:
;;;   Types:      int, long, bool (in expressions)
;;;               Array<int>      (in expressions)
;;;               (int, int)      (tuples, in expressions)
;;;   Variables:  always int (declared with var, assigned, referenced)
;;;   Stmts:      if/else, for(i < N), var decl, assign, expr stmt
;;;   Exprs:      arithmetic (+,-,*,/,%,neg), comparisons, boolean,
;;;               ternary if(c,t,f), int↔long casts, array literals,
;;;               safe array index, tuple construction, tuple field access
;;;
;;; Determinism guarantees:
;;;   - Division/modulo always guarded: if(r==0, safe_val, a op b)
;;;   - Array access always safe:       arr[(i & 0x7fffffff) % arr.length]
;;;   - All loops bounded by a compile-time constant limit
;;;   - No recursion
;;;   - No use of uninitialized memory or undefined behavior

(require xsmith
         racr
         racket/string
         racket/format
         racket/list)

;;; ============================================================
;;; Spec component
;;; ============================================================
(define-spec-component virgil)

;;; ============================================================
;;; Type algebra
;;; All types are base-types with unique symbols to keep
;;; unification simple (no parametric polymorphism in Phase 1).
;;; ============================================================
(define int-t    (base-type 'int))
(define long-t   (base-type 'long))
(define bool-t   (base-type 'bool))
(define void-t   (base-type 'void))
(define iarr-t   (base-type 'iarr))     ;; Array<int>
(define iipair-t (base-type 'iipair))   ;; (int, int)

;; Render a type as a Virgil type string
(define (type->str t)
  (cond [(equal? t int-t)    "int"]
        [(equal? t long-t)   "long"]
        [(equal? t bool-t)   "bool"]
        [(equal? t iarr-t)   "Array<int>"]
        [(equal? t iipair-t) "(int, int)"]
        [else                "int"]))

;;; ============================================================
;;; Grammar
;;; ============================================================
(add-to-grammar virgil

  ;; ----------------------------------------------------------
  ;; Top-level program: one component, one main method.
  ;; ----------------------------------------------------------
  [Program #f
    ([body : MainBlock])]

  ;; ----------------------------------------------------------
  ;; Main block: parameter 'a', then declarations, then
  ;; statements, then a final return.
  ;; strict-child-order? ensures 'a' is in scope for decls,
  ;; and decls are in scope for stmts.
  ;; ----------------------------------------------------------
  [MainBlock #f
    ([aparam : MainParam]          ;; binds 'a : int' in scope
     [decls  : VarDecl *]         ;; var v0, v1, ...
     [stmts  : Stmt *]
     [ret    : ReturnStmt])
    #:prop strict-child-order? #t]

  ;; Main parameter — creates a binding for 'a' (int).
  ;; Fixed name via the fresh property below.
  ;; binder-style definition makes it visible to sibling
  ;; children of MainBlock that come after it (decls, stmts, ret).
  [MainParam #f (name type)
    #:prop binder-info ()]

  ;; ----------------------------------------------------------
  ;; Variable declaration: var vN: int = <expr>;
  ;; All declared variables are int for simplicity.
  ;; ----------------------------------------------------------
  [VarDecl #f
    (name type [init : Expr])
    #:prop binder-info ()]

  ;; ----------------------------------------------------------
  ;; Statements
  ;; ----------------------------------------------------------
  [Stmt #f ()
    #:prop may-be-generated #f]

  [IfStmt Stmt
    ([cond : Expr]
     [then : NestedBlock]
     [else : NestedBlock])]

  ;; Bounded for-range: for (iN < LIMIT) { ... }
  ;; ivar is a plain name field generated by the fresh property.
  ;; We don't use Xsmith's binder mechanism here (ForRange is a void
  ;; statement, so its type would conflict with the int binder type).
  ;; Body statements can reference outer variables via VarRefE.
  [ForRange Stmt
    ([ivar  = #f]
     [limit = (+ 1 (random 8))]
     [body  : NestedBlock])]

  ;; Assignment to an existing int variable
  [AssignStmt Stmt
    ([target : VarRefE]
     [val    : Expr])]

  ;; Discard expression result (useful for side-effect-free but
  ;; structurally interesting expressions)
  [ExprStmt Stmt
    ([e : Expr])]

  ;; ----------------------------------------------------------
  ;; Nested block: appears inside if/for bodies.
  ;; Does not declare new variables (keeps scoping flat).
  ;; ----------------------------------------------------------
  [NestedBlock #f
    ([stmts : Stmt *])]

  ;; ----------------------------------------------------------
  ;; Return statement: always returns int.
  ;; ----------------------------------------------------------
  [ReturnStmt #f
    ([val : Expr])]

  ;; ----------------------------------------------------------
  ;; Expressions
  ;; ----------------------------------------------------------
  [Expr #f ()
    #:prop may-be-generated #f]

  ;; --- Literals ---
  [IntLit  Expr ([v = (- (random 2001) 1000)])]
  [LongLit Expr ([v = (- (random 200001) 100000)])]
  [BoolLit Expr ([v = (zero? (random 2))])]

  ;; --- Variable reference (always int) ---
  ;; 'name' is a plain field so the reference-info mechanism can resolve it.
  [VarRefE Expr (name)
    #:prop reference-info (read)]

  ;; --- Int arithmetic ---
  [IAdd Expr ([l : Expr] [r : Expr])]
  [ISub Expr ([l : Expr] [r : Expr])]
  [IMul Expr ([l : Expr] [r : Expr])]
  ;; Safe division: rendered as  if(r == 0, l, l / r)
  [IDiv Expr ([l : Expr] [r : Expr])]
  ;; Safe modulo:   rendered as  if(r == 0, 0, l % r)
  [IMod Expr ([l : Expr] [r : Expr])]
  [INeg Expr ([e : Expr])]

  ;; --- Long arithmetic ---
  [LAdd Expr ([l : Expr] [r : Expr])]
  [LSub Expr ([l : Expr] [r : Expr])]
  [LMul Expr ([l : Expr] [r : Expr])]
  [LNeg Expr ([e : Expr])]

  ;; --- Int comparisons (produce bool) ---
  [ICmp Expr
    ([l  : Expr]
     [r  : Expr]
     [op = (list-ref '("==" "!=" "<" "<=" ">" ">=") (random 6))])]

  ;; --- Boolean logic ---
  [BAnd Expr ([l : Expr] [r : Expr])]
  [BOr  Expr ([l : Expr] [r : Expr])]
  [BNot Expr ([e : Expr])]

  ;; --- Ternary if-expression: int-t only to avoid iipair/iarr holes ---
  [IfE Expr ([c : Expr] [t : Expr] [f : Expr])]

  ;; --- Int ↔ Long conversions ---
  [IntToLong Expr ([e : Expr])]   ;; long.!(int_expr)  -- safe widening
  [LongToInt Expr ([e : Expr])]   ;; int.view(long)    -- bit-truncation, no throw

  ;; --- Array<int>: inline construction to avoid iarr-t holes ---
  ;; SafeArrGet: [e0, e1, ...][(idx & 0x7fffffff) % N]
  ;; (generates and accesses an inline array of 1–4 int elements)
  [SafeArrGet Expr
    ([elems : Expr * = (+ 1 (random 4))]   ;; int-t elements
     [idx   : Expr])]                        ;; int-t index
  ;; SafeArrLen: [e0, e1, ...].length  (int result = literal count)
  [SafeArrLen Expr
    ([elems : Expr * = (+ 1 (random 4))])]

  ;; --- (int, int) tuples: inline construction to avoid iipair-t holes ---
  ;; SafePairFst: (a, b).0  — always returns the first component
  [SafePairFst Expr ([a : Expr] [b : Expr])]
  ;; SafePairSnd: (a, b).1  — always returns the second component
  [SafePairSnd Expr ([a : Expr] [b : Expr])]
)

;;; ============================================================
;;; Type info
;;; ============================================================
(add-property virgil type-info

  ;; Structure
  [Program    [void-t (λ (n t) (hash 'body void-t))]]
  ;; MainParam and VarDecl are binder nodes; their type-info type
  ;; must match the binding type (int-t) so Xsmith's type unification
  ;; between the node type and the stored type field succeeds.
  [MainBlock  [void-t (λ (n t) (hash 'aparam int-t
                                      'decls  (λ (cn) int-t)
                                      'stmts  (λ (cn) void-t)
                                      'ret    void-t))]]
  [MainParam  [int-t  (λ (n t) (hash))]]
  ;; VarDecl is a binder: its node type = binding type = int-t
  [VarDecl    [int-t  (λ (n t) (hash 'init int-t))]]
  [ReturnStmt [void-t (λ (n t) (hash 'val  int-t))]]

  ;; Statements
  [IfStmt     [void-t (λ (n t) (hash 'cond bool-t 'then void-t 'else void-t))]]
  [ForRange   [void-t (λ (n t) (hash 'body void-t))]]
  [AssignStmt [void-t (λ (n t) (hash 'target int-t 'val int-t))]]
  [ExprStmt   [void-t (λ (n t) (hash 'e (fresh-type-variable)))]]
  [NestedBlock [void-t (λ (n t) (hash 'stmts void-t))]]

  ;; Literals
  [IntLit  [int-t  (λ (n t) (hash))]]
  [LongLit [long-t (λ (n t) (hash))]]
  [BoolLit [bool-t (λ (n t) (hash))]]

  ;; Variable reference — always int (only int vars in scope)
  [VarRefE [int-t (λ (n t) (hash))]]

  ;; Int arithmetic
  [IAdd [int-t (λ (n t) (hash 'l int-t 'r int-t))]]
  [ISub [int-t (λ (n t) (hash 'l int-t 'r int-t))]]
  [IMul [int-t (λ (n t) (hash 'l int-t 'r int-t))]]
  [IDiv [int-t (λ (n t) (hash 'l int-t 'r int-t))]]
  [IMod [int-t (λ (n t) (hash 'l int-t 'r int-t))]]
  [INeg [int-t (λ (n t) (hash 'e int-t))]]

  ;; Long arithmetic
  [LAdd [long-t (λ (n t) (hash 'l long-t 'r long-t))]]
  [LSub [long-t (λ (n t) (hash 'l long-t 'r long-t))]]
  [LMul [long-t (λ (n t) (hash 'l long-t 'r long-t))]]
  [LNeg [long-t (λ (n t) (hash 'e long-t))]]

  ;; Comparisons and logic
  [ICmp [bool-t (λ (n t) (hash 'l int-t 'r int-t))]]
  [BAnd [bool-t (λ (n t) (hash 'l bool-t 'r bool-t))]]
  [BOr  [bool-t (λ (n t) (hash 'l bool-t 'r bool-t))]]
  [BNot [bool-t (λ (n t) (hash 'e bool-t))]]

  ;; Ternary: restricted to int-t so branches never need iarr/iipair
  [IfE [int-t (λ (n t) (hash 'c bool-t 't int-t 'f int-t))]]

  ;; Conversions
  [IntToLong [long-t (λ (n t) (hash 'e int-t))]]
  [LongToInt [int-t  (λ (n t) (hash 'e long-t))]]

  ;; Arrays: inline form — all children are int-t (no iarr-t holes)
  [SafeArrGet [int-t (λ (n t) (hash 'elems (λ (cn) int-t) 'idx int-t))]]
  [SafeArrLen [int-t (λ (n t) (hash 'elems (λ (cn) int-t)))]]

  ;; Tuples: inline form — all children are int-t (no iipair-t holes)
  [SafePairFst [int-t (λ (n t) (hash 'a int-t 'b int-t))]]
  [SafePairSnd [int-t (λ (n t) (hash 'a int-t 'b int-t))]]
)

;;; ============================================================
;;; Lift-type → binder type
;;; With more than one binder form (MainParam, VarDecl), Xsmith needs
;;; to know which binder to generate when "lifting" a new binding.
;;; MainParam is a parameter (fixed, "a"); VarDecl is the natural
;;; choice for any lifted int binding.
;;; ============================================================
(add-property virgil lift-type->ast-binder-type
  [#f (λ (type) 'VarDecl)])

;;; ============================================================
;;; Fresh property
;;; Set type fields for binder nodes (all variables are int-t).
;;; Force the fixed name "a" for the main parameter.
;;; ============================================================
(add-property virgil fresh
  ;; VarDecl: type field must hold the Xsmith type for scope lookup
  [VarDecl   (λ (n) (hash 'type int-t))]
  ;; ForRange: generate a loop variable name; ivar is not in Xsmith scope
  [ForRange  (λ (n) (hash 'ivar (format "i~a" (random 10000))))]
  ;; MainParam: force name "a" so renders use "a", type is int
  [MainParam (λ (n) (hash 'name "a" 'type int-t))])

;;; ============================================================
;;; Render
;;; ============================================================
(define (render n)
  (att-value 'xsmith_render-node n))

;; Indent each line of a multi-line string by N spaces
(define (indent str n)
  (define pad (make-string n #\space))
  (string-join
   (map (λ (l) (string-append pad l))
        (string-split str "\n" #:trim? #f))
   "\n"))

(add-property virgil render-node-info

  ;; ---- Program ----
  ;; A top-level main (no enclosing component) so that compiled test binaries
  ;; are named after the source file, as the test runners expect.
  [Program (λ (n)
    (format "def main(a: int) -> int {\n~a\n}\n"
            (render (ast-child 'body n))))]

  ;; ---- MainBlock ----
  ;; aparam is a phantom node (no output), decls and stmts are lines,
  ;; ret is the return statement.
  [MainBlock (λ (n)
    (define lines '())
    (for ([d (ast-children (ast-child 'decls n))])
      (set! lines (cons (string-append "    " (render d)) lines)))
    (for ([s (ast-children (ast-child 'stmts n))])
      (set! lines (cons (string-append "    " (render s)) lines)))
    (set! lines (cons (string-append "    " (render (ast-child 'ret n))) lines))
    (string-join (reverse lines) "\n"))]

  ;; MainParam produces no text — its name "a" is injected into scope only
  [MainParam (λ (n) "")]

  ;; ---- VarDecl ----
  [VarDecl (λ (n)
    (format "var ~a: int = ~a;"
            (ast-child 'name n)
            (render (ast-child 'init n))))]

  ;; ---- ReturnStmt ----
  [ReturnStmt (λ (n)
    (format "return ~a;" (render (ast-child 'val n))))]

  ;; ---- IfStmt ----
  [IfStmt (λ (n)
    (define cond-str (render (ast-child 'cond n)))
    (define then-str (render (ast-child 'then n)))
    (define else-str (render (ast-child 'else n)))
    (format "if (~a) {\n~a\n    } else {\n~a\n    }"
            cond-str then-str else-str))]

  ;; ---- ForRange ----
  [ForRange (λ (n)
    (format "for (~a < ~a) {\n~a\n    }"
            (ast-child 'ivar n)
            (ast-child 'limit n)
            (render (ast-child 'body n))))]

  ;; ---- AssignStmt ----
  [AssignStmt (λ (n)
    (format "~a = ~a;"
            (render (ast-child 'target n))
            (render (ast-child 'val n))))]

  ;; ---- ExprStmt ----
  [ExprStmt (λ (n)
    (format "~a;" (render (ast-child 'e n))))]

  ;; ---- NestedBlock ----
  [NestedBlock (λ (n)
    (define stmts (ast-children (ast-child 'stmts n)))
    (if (null? stmts)
        ""
        (string-join
         (map (λ (s) (string-append "        " (render s))) stmts)
         "\n")))]

  ;; ---- Literals ----
  [IntLit  (λ (n) (~a (ast-child 'v n)))]
  [LongLit (λ (n) (format "~aL" (ast-child 'v n)))]
  [BoolLit (λ (n) (if (ast-child 'v n) "true" "false"))]
  [VarRefE (λ (n) (ast-child 'name n))]

  ;; ---- Int arithmetic ----
  [IAdd (λ (n) (format "(~a + ~a)"  (render (ast-child 'l n)) (render (ast-child 'r n))))]
  [ISub (λ (n) (format "(~a - ~a)"  (render (ast-child 'l n)) (render (ast-child 'r n))))]
  [IMul (λ (n) (format "(~a * ~a)"  (render (ast-child 'l n)) (render (ast-child 'r n))))]
  [IDiv (λ (n)
    (define l (render (ast-child 'l n)))
    (define r (render (ast-child 'r n)))
    ;; if(r == 0, l, l / r)  — Virgil ternary if-expression
    (format "if(~a == 0, ~a, ~a / ~a)" r l l r))]
  [IMod (λ (n)
    (define l (render (ast-child 'l n)))
    (define r (render (ast-child 'r n)))
    (format "if(~a == 0, 0, ~a % ~a)" r l r))]
  [INeg (λ (n) (format "(-(~a))" (render (ast-child 'e n))))]

  ;; ---- Long arithmetic ----
  [LAdd (λ (n) (format "(~a + ~a)" (render (ast-child 'l n)) (render (ast-child 'r n))))]
  [LSub (λ (n) (format "(~a - ~a)" (render (ast-child 'l n)) (render (ast-child 'r n))))]
  [LMul (λ (n) (format "(~a * ~a)" (render (ast-child 'l n)) (render (ast-child 'r n))))]
  [LNeg (λ (n) (format "(-(~a))" (render (ast-child 'e n))))]

  ;; ---- Comparisons (int → bool) ----
  [ICmp (λ (n)
    (format "(~a ~a ~a)"
            (render (ast-child 'l n))
            (ast-child 'op n)
            (render (ast-child 'r n))))]

  ;; ---- Boolean logic ----
  [BAnd (λ (n) (format "(~a && ~a)" (render (ast-child 'l n)) (render (ast-child 'r n))))]
  [BOr  (λ (n) (format "(~a || ~a)" (render (ast-child 'l n)) (render (ast-child 'r n))))]
  [BNot (λ (n) (format "(!~a)" (render (ast-child 'e n))))]

  ;; ---- Ternary ----
  [IfE (λ (n)
    (format "if(~a, ~a, ~a)"
            (render (ast-child 'c n))
            (render (ast-child 't n))
            (render (ast-child 'f n))))]

  ;; ---- Int ↔ Long ----
  [IntToLong (λ (n) (format "long.!(~a)" (render (ast-child 'e n))))]
  ;; int.view for bit-truncation (no range check, never throws)
  [LongToInt (λ (n) (format "int.view(~a)" (render (ast-child 'e n))))]

  ;; ---- Arrays (inline form — no iarr-t holes) ----
  ;; SafeArrGet: [e0, e1, ...][(idx & 0x7fffffff) % N]
  [SafeArrGet (λ (n)
    (define elems (ast-children (ast-child 'elems n)))
    (define n-elems (length elems))
    (define arr-str (string-append "[" (string-join (map render elems) ", ") "]"))
    (define idx-str (render (ast-child 'idx n)))
    (format "~a[(~a & 0x7fffffff) % ~a]" arr-str idx-str n-elems))]
  ;; SafeArrLen: [e0, e1, ...].length
  [SafeArrLen (λ (n)
    (define elems (ast-children (ast-child 'elems n)))
    (define arr-str (string-append "[" (string-join (map render elems) ", ") "]"))
    (format "~a.length" arr-str))]

  ;; ---- Tuples (inline form — no iipair-t holes) ----
  ;; SafePairFst: (a, b).0  — evaluates both, returns first
  [SafePairFst (λ (n)
    (format "(~a, ~a).0" (render (ast-child 'a n)) (render (ast-child 'b n))))]
  ;; SafePairSnd: (a, b).1  — evaluates both, returns second
  [SafePairSnd (λ (n)
    (format "(~a, ~a).1" (render (ast-child 'a n)) (render (ast-child 'b n))))]
)

;;; ============================================================
;;; Xsmith interface + entry point
;;; ============================================================
(define-xsmith-interface-functions
  [virgil]
  #:program-node Program
  #:fuzzer-name  virgil
  #:comment-wrap (λ (lines)
    (string-join (map (λ (l) (string-append "// " l)) lines) "\n")))

(provide virgil-generate)
(module+ main
  (virgil-command-line))
