#!/bin/bash
TMP=$1
p=$2
FLAGS=$3
FILES=$4
if [ "$HEAP_SIZE" = "" ]; then
  HEAP_SIZE=100m
fi
v3c-wave -heap-size=$HEAP_SIZE -output=$TMP $FLAGS $FILES
if [ $? = 0 ]; then
	echo wave $TMP/${p}.wasm
else
	exit $?
fi
